### ISSUE TITLE
pap tt

### ISSUE THREAD

**Issue by widnyana** [my-dvr/GUIDE.md#1]
lmao

**Comment by codenoid** [comment]
astagfirullah, ngga ada ahlak

**Comment by widnyana** [comment]
@codenoid hey, where's your comment anyway? seems it got deleted

**Comment by codenoid** [comment]
![azagRWng_700w_0](https://user-images.githubusercontent.com/14269809/82977879-5f2c9e00-a00d-11ea-9867-0c8db0ba00b8.jpg)
